# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a3398cd54de99a10ca43d486f136603a9e5a93da5c1704fbefac44302ea97ea2c073a934a4dbebbd3df5560a7748880b9d31cc0377ea262b5dc29d70c327254

test:
  secret_key_base: 8aa404d27d222916e7f2fda92615cec0af6dfb2fcce517f1bbc2e388701da7dde768cc7c9c7746371ba977ef33b9e3edba007488f80002761b0e060988940fbd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
