# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9664165051e166304654ebb0a26a92f12f3b150c63f471256ffd0ed2b30d4c47aad46c72f76a0df716a9249a45af2b9ee47a417a9c5583b558007cf1a7e0e842

test:
  secret_key_base: 8d99ecf89da1be43be31dc561213c0e72a633a1786c1354bd7112d1d40443475225103bb5576d7ba2354b9ca484bd1b4782c74e3f43ddcd43dd48767978f7ffc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
